---
title: "conversation_by_role"
author: "David Hood"
date: "02/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache.path = "../cache")
```

```{r libraries}
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggridges))
suppressPackageStartupMessages(library(ggthemes))
```

```{r load_data, cache=TRUE}
set1 = "../fprog/canadian_racists"
set2 = "../fprog/mol_racist"
set3 = "../fprog/South_racist"
set4 = "../fprog/recent_direct"
set5 = "../fprog/recent_direct_regather600"
f1 <- paste0(set1, "/", list.files(set1, pattern=".csv$"))
f2 <- paste0(set2, "/", list.files(set2, pattern=".csv$"))
f3 <- paste0(set3, "/", list.files(set3, pattern=".csv$"))
f4 <- paste0(set4, "/", list.files(set4, pattern=".csv$"))
f5 <- paste0(set5, "/", list.files(set5, pattern=".csv$"))
full_list = c(f1,f2,f3,f4,f5)

v_for_visitor <- bind_rows(lapply(full_list, read_csv, col_types=cols(
    .default = col_character()))) %>% distinct() 
o_for_offshore <- read.csv("~/Syncplicity Folders/support_files/assignment.csv", colClasses = "character") %>%
    mutate(user_id = paste0("x", user_id))
a_for_authoritarian <-  read.csv("~/Syncplicity Folders/support_files/fa_spec.csv", colClasses = "character") %>%
    mutate(user_id = xliker, 
           nett_nz = as.numeric(nett_nz),
           nett_fa = as.numeric(nett_fa), 
           nett_au = as.numeric(nett_au),
           nett_gb = as.numeric(nett_gb),
           nett_us = as.numeric(nett_us),
           nz0 = nett_nz/ 12, 
           fa0 = nett_fa/ 15,
           au0 = nett_au/ 12,
           gb0 = nett_gb/ 11,
           us0 = nett_us/ 10,
           allike =as.numeric(allike))

joined_data <- v_for_visitor %>% inner_join(o_for_offshore, by="user_id") %>%
    inner_join(a_for_authoritarian, by="user_id") %>% 
    filter(locat %in% c("AU", "NZ", "US", "GB")) %>%
    mutate(af = nett_nz * (locat == "NZ") + nett_au * (locat == "AU") +
               nett_gb * (locat == "GB") + nett_us * (locat == "US"),
           af0 = nz0 * (locat == "NZ") + au0 * (locat == "AU") +
               gb0 * (locat == "GB") + us0 * (locat == "US"),
               balance = fa0-af0, interest = (af + nett_fa)/allike)

```

Attempt at a graph 

```{r fig.height=10}
joined_data %>% 
    mutate(is_NZ = locat == "NZ",
           hour_of_day = as.factor(hour(created_at) + is_NZ/2)) %>% 
    ggplot(aes(x=balance, y=hour_of_day, fill=is_NZ,group=NULL)) + 
    geom_density_ridges(panel_scaling=FALSE, rel_min_height=0.01, alpha=0.5) +
    geom_vline(xintercept = 0) + theme_tufte()
```

```{r fig.height=10}
joined_data %>%
    mutate(is_NZ = locat == "NZ") %>%
    ggplot(aes(x=balance, fill=is_NZ)) + 
    geom_histogram(binwidth = 0.5) + theme_tufte()
```


```{r fig.height=5}
joined_data %>%
    mutate(is_NZ = locat == "NZ",
           hour_of_day = hour(created_at)) %>% 
    group_by(hour_of_day) %>% summarise(propNZ = sum(is_NZ)/ n()) %>%
    ggplot(aes(x=hour_of_day, y=propNZ)) + 
    geom_col() + theme_tufte() + coord_polar()
```

```{r fig.height=5}
joined_data %>%
    mutate(hour_of_day = hour(created_at)) %>% 
    count(locat, hour_of_day) %>%
    ggplot(aes(x=hour_of_day, y=n)) + facet_wrap(~locat, ncol=2) +
    geom_col() + theme_tufte() + coord_polar()
```

NZ hist

```{r fig.height=5}
joined_data %>%
    filter(locat ==  "NZ") %>% 
    ggplot(aes(x=balance)) +
    geom_histogram(binwidth = 0.5) + theme_tufte() 
```

Scattergraph

```{r fig.height=6}
joined_data %>%
    select(user_id, balance, locat, interest) %>% distinct() %>%
    ggplot(aes(x=balance, y=log2(interest), colour=locat)) + 
    geom_jitter(size=0.1, alpha=0.3, width=0.1, height=0.5) +
    facet_wrap(~ locat, ncol=2) + theme_tufte() + coord_cartesian(xlim=c(-10,10))


```



NZonly- accounts involved, how much they follow alt-right (x) vs how many posts(y)

```{r fig.height=6}
joined_data %>%
    count(user_id, balance, locat, interest) %>% distinct() %>%
    ggplot(aes(x=balance, y=n, colour=locat)) + 
    geom_vline(xintercept = 0, colour="#AAAAAA") +
    geom_jitter(size=.1, alpha=0.1, width=0.1, height=0.5) +
    theme_tufte() + coord_cartesian(xlim=c(-8,8), ylim=c(0,180)) +facet_wrap(~ locat, ncol=2)
    
```






